%{ 
Universidade Federal de Uberlãndia
Laboratório de Engenharia Biomédica - BioLab

Script responsável por gerar png dos dados de um arquivo AEDAT gravado
em uma DVS128
%}
clc;
clear all;
close all;
%{
addpath('C:/Users/Samsung/Documents/Mestrado/Hand stuff/AEDAT tools/Matlab/Files generator/Functions/');
addpath('C:/Users/Samsung/Documents/Mestrado/Hand stuff/Datasource/AEDAT_files/');
%}
addpath('Functions/');
addpath('./././Datasource/AEDAT_files/');
originPathOfAEDATfiles = 'C:/Users/Samsung/Documents/Mestrado/HandStuff/Datasource/AEDAT_files/';
%% Carregar o vídeo
file = {};
file.importParams = {};
source = {'Mouse.aedat'...1
        ,'Lapiseira.aedat'...2
        ,'Cubo.aedat'};%3

file.importParams.source = 'Dvs128';

%% Gerar arquivos png
for i=1:length(source)
    
    file.importParams.filePath = source{i};
    AEDAT = ImportAedat(file);
    
    [ t,to,tf,deltaT ] = GetTimeInformation( AEDAT );
    timeStep = 300000; % 300000us / 300 ms

    pathSaveData = 'C:/Users/Samsung/Documents/Mestrado/HandStuff/Datasource/PNG_files/';
    label = strtok(file.importParams.filePath,'.');
    GerarArquivosPNG(AEDAT,label,pathSaveData,timeStep);
    
end
%% write an txt file
fid=fopen('C:/Users/Samsung/Documents/Mestrado/HandStuff/Datasource/PNG_files/README.txt','wt');
fprintf(fid, ['------------------- README -------------------' '\r\n']);
fprintf(fid, ['FILES GENERATED BY SCRIPT' '\r\n']);
fprintf(fid, ['Date: ' date '\r\n']);
fprintf(fid,['timeStep: ' int2str(timeStep) ' [us] \r\n']);
fprintf(fid,['origin path of aedat files: ' originPathOfAEDATfiles '\r\n']);
constantes = Constantes();
fprintf(fid,['full time of records: ' int2str(constantes.tempoGravacao) ' [s] \r\n']);
fprintf(fid,['amount of record in each class: '  int2str(constantes.tempoGravacao/(timeStep*10^-6)) ' [un] \r\n']);
fprintf(fid,['degrees between images: '  num2str(360.0 / (constantes.tempoGravacao/(timeStep*10^-6))) ' [º] \r\n']);
for i=1:length(source)
    fprintf(fid,['files used to generate data:' source{i} '\r']);    
end
fclose(fid);true
